#!/usr/bin/with-contenv bash

echo "creating nginx config directories..."
# Create directories for nginx
mkdir -p /config/{nginx/sites-enabled,logs/nginx,logs/nginx/sites,rules,conf.d,certs}
if [ $? ] then
  echo " creating nginx config directories... complete"
fi

if [ ! -f /config/nginx/nginx.conf ] then
  echo "copying default nginx configuration files..."
  # copy default config files to the /config/nginx folder only if they do not exist

  for CONFIGURATION in /default/*; do
    if [ ! -f /config/nginx/${CONFIGURATION} ] && [ "${CONFIGURATION}" != "index.html" ] then
      cp /defaults/${CONFIGURATION} /config/nginx/${CONFIGURATION} \
      echo "${CONFIGURATION} copied"
    fi
  elif then
      cp /defaults/${CONFIGURATION} /www/${CONFIGURATION} \
      echo "${CONFIGURATION} copied"
    fi
  done
fi

# set ownership and permissions
chown -R abc:abc /config
chmod -R g+w /config/nginx /www
chmod -R 644 /etc/logrotate.d
